{% set name = "reorder_python_imports" %}
{% set version = "3.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/reorder_python_imports-{{ version }}.tar.gz
  sha256: bcc4e5e467a8833ec187e35f84f1a3e442881b3c62c265ece87677100473db43

build:
  entry_points:
    - reorder-python-imports = reorder_python_imports:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ={{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - classify-imports >=4.1

test:
  imports:
    - reorder_python_imports
  commands:
    - pip check
    - reorder-python-imports --help
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/asottile/reorder-python-imports
  summary: Tool for reordering python imports
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
